### ISSUE TITLE
kmod-tun

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#10]
The official fw does not have tun enabled (yet).

Could you please enable it?

**Comment by Kra1o5** [comment]
TUN support is already present.

Check: https://github.com/piccolo-dev/android_kernel_bq_piccolo/blob/cm-12.1-test/arch/arm/configs/cyanogenmod_piccolo_defconfig#L1304

**Comment by piwats** [comment]
Ah, thank you very much.

**Comment by Kra1o5** [comment]
No problem.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#10
