### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by pinox12** [piccolo-dev/android_device_bq_piccolo#12]
Couldn't add widget.
https://goo.gl/photos/ZXTT45aNgxNfdmjt6

**Comment by Kra1o5** [comment]
Is really weird, @eloimuns can you test it?

**Comment by andy-de** [comment]
I don't think it's a bug. The "couldn't add widget" is a placeholder, if the searchbar of the Google Search App couldn't be loaded (Usually, at this position is the Google Searchbar). If you deleted the Google Search App or if you have frozen the app, the "widget" ist not available.

The "placeholder" can be hidden by using the GravityBox Xposed Module, if you want.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#12
