### ISSUE TITLE
Hotspot "disabled due to sim subscription change"

### ISSUE THREAD

**Issue by Marty6** [piccolo-dev/android_device_bq_piccolo#13]
When my phone is in place with a rather poor signal, **WiFi Tethering disables itself regularly** saying that the hotspot was "disabled due to sim subscription change".

Using the same SIM card in the same place with a mobile WiFi hotspot (MiFi), the Internet connection works perfectly.

**Comment by Kra1o5** [comment]
Hi @Marty6 ,

I & @eloimuns , will check it asap.

Greetings

**Comment by cmorlok** [comment]
This (bad) behavior has been introduced to CM12.1 here: http://review.cyanogenmod.org/#/c/109021/ 

A fix has already been merged on Dec 9th: http://review.cyanogenmod.org/#/c/122778

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#13
