### ISSUE TITLE
SIM cards not recognized after encryption

### ISSUE THREAD

**Issue by andristeiner** [piccolo-dev/android_device_bq_piccolo#14]
I've encrypted the phone trough the Android default way ("Settings" > "Security" > "Encrypt phone"). Everything went fine so far, however the SIM cards are not recognized anymore. Its just like they're not inserted at all ("SIM empty" in "Settings" > "SIM Cards"). After restoring a unencrypted backup, everything is fine again without changing anything hardware related.

**Comment by Kra1o5** [comment]
Thanks for the feedback @andristeiner 

Can you provide a log with encrypted phone?

@eloimuns can you check it?

**Comment by andristeiner** [comment]
What do you need exactly? Is there a documentation somewhere? I'm not very into the whole process yet, sorry. I know "adb logcat", do you need it's output? If yes, from the whole bootup or when does the interesting stuff happen?

**Comment by Kra1o5** [comment]
Hi @andristeiner ,

Sorry for big delay.

Do IT with app "Catlog"  from playstore.

**Comment by cmorlok** [comment]
This could be the solution: http://review.cyanogenmod.org/#/c/117861/1

**Comment by Kra1o5** [comment]
Hi @andristeiner ,

Thanks @cmorlok .

Now in our repos.

Included in cm-12.1-20151227-UNOFFICIAL-piccolo.

GreEtings

**Comment by cmorlok** [comment]
While this hack does actually fixes the issue, it shouldn't be necessary unless we also build for single SIM devices.

Instead ril-daemon2 should not be disabled in init.qcom.rc. This is only useful when persist.radio.multisim.config is set in init.c.

**Comment by Kra1o5** [comment]
We can remove the prop & start service by default.

**Comment by andristeiner** [comment]
Verified, works with  cm-12.1-20151227-UNOFFICIAL-piccolo now, thank you.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#14
