### ISSUE TITLE
SIM number not assigned if roaming

### ISSUE THREAD

**Issue by antonioborondo** [piccolo-dev/android_device_bq_piccolo#15]
If one of the SIM cards is on roaming, the phone number is not assigned:

![sim](https://cloud.githubusercontent.com/assets/5370877/11302427/4d438a2e-8f95-11e5-940b-2ee000367ca8.png)

**Comment by Kra1o5** [comment]
Hi @antonioborondo ,

Sorry for the big delay.

Is normal behavior at least with spanish SIM.

Using single or dual SIM.

**Comment by antonioborondo** [comment]
Hi @Kra1o5,

Thanks for the info.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#15
