### ISSUE TITLE
AOSP Keyboard: is motion typing like swiftkey working?

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#16]
Here on 20151121 I noticed that the motion like typing aka swiftkey isn't working despite the appropriate options/settings set.

Is this a bug or do I miss something?

**Comment by stucki** [comment]
I'm using Swiftkey too but don't miss any features. Can you please explain in more detail what doesn't work?

**Comment by piwats** [comment]
sorry for the misleading "swiftkey" naming.

In the android keyboard settings, there under "gesture typing", all options are enabled, that is gesture typing should work.

Now, when I try to "gesture" a word, no trail, no nothing comes, as if any gesture typing is on. only letter popups pop up on each letter, but no trail is seen.

**Comment by piwats** [comment]
Ah, I got it.

https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options

put swypelibs in .gapps-config/gapps-config.txt to get the gesture typing working when installing open gapps.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#16
