### ISSUE TITLE
"Always ask" option for calls lost on every restart

### ISSUE THREAD

**Issue by Marty6** [piccolo-dev/android_device_bq_piccolo#17]
In SIM Card settings I chose the option "Always ask" for phone calls.

Unfortunately, after every reboot, this option reverts back to one of my SIM cards.

**Comment by Kra1o5** [comment]
Hi @Marty6 ,

Im only use one SIM slot.

Maybe other can try this.

**Comment by piwats** [comment]
Can confirm:

When I set data to sim2, sms/mms and phone calls to sim1, the settings are all then reverted back to sim2 on reboot.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#17
