### ISSUE TITLE
Double tap on screen is sometimes not working.

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#18]
Hi,

I've noticed that the double tap on screen to wake the phone up is sometimes not working.

To fix this I turn of and on again double taping in the settings. Then it starts to work again, at least for some time.

After some time double tap is gone again.

Does anybody have this issue, too?

**Comment by Kra1o5** [comment]
Hi @piwats ,

I cant reproduce it.

**Comment by piwats** [comment]
Its even hard for me to track it down.

 There is another report about it on android-hilfe.de forums.

It appears that it happens sporadically. One time double tap is gone, another it is back and working.

I try to log it with logcat.

**Comment by piwats** [comment]
With today's update I do not notice any problems. At least yet.

**Comment by piwats** [comment]
20151221: sometimes double tap isn't working.

**Comment by piwats** [comment]
dmesg output number 1 when double tap isn't working

[20151221-dmesg.txt](https://github.com/piccolo-dev/android_device_bq_piccolo/files/70927/20151221-dmesg.txt)

and when double tap started to work.

[20151221-dmesg-double-tap-working-again.txt](https://github.com/piccolo-dev/android_device_bq_piccolo/files/70928/20151221-dmesg-double-tap-working-again.txt)

Sorry if they may overlap.

**Comment by piwats** [comment]
It may be csused by too dry fingers. At least that is my observation. I'm closing this issue therefore.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#18
