### ISSUE TITLE
Does the M5 support Galileo?

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#19]
Hello,

I can't find any information on the snapdragon 615 and its GNSS chipset, the iZat Gen8c.

Do you know whether our device supports the Galileo GNSS?

It does support Beidou, which is very similar to Galileo.

I know that Galileo has not reached FOC yet, but still it is very interesting to know.

**Comment by Kra1o5** [comment]
Hi @piwats in theory yes.

**Comment by cmorlok** [comment]
The 615 has the same GNSS (IZat Gen8C) like the 810. And the latter does
support Galileo:
https://www.qualcomm.com/news/releases/2015/02/02/qualcomm-snapdragon-810-processor-powers-premium-tier-mobile-experiences

So, yes, it should support Galileo. If it will not support it officially,
we will still be able to use the blobs from an 808/810 device and look of
it works.
Am 17.12.2015 6:56 nachm. schrieb "Alejandro Lopez" <
notifications@github.com>:

**Comment by piwats** [comment]
As we won't see Galileo soon, I'll close this one.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#19
