### ISSUE TITLE
No SIM

### ISSUE THREAD

**Issue by DocMAX** [piccolo-dev/android_device_bq_piccolo#2]
No SIM. \firmware empty

**Comment by Kra1o5** [comment]
So, firmware not get mounted?

**Comment by DocMAX** [comment]
Seems so. I have the 3GB/32GB version.

**Comment by Kra1o5** [comment]
You can give us logcat/dmesg?

**Comment by DocMAX** [comment]
Yes, here is the Logcat. Rename to .zip
 
![logcat](https://cloud.githubusercontent.com/assets/5351323/9975725/04184eba-5ec7-11e5-9bf5-4b4a37956051.jpg)

**Comment by Kra1o5** [comment]
Sorry I cant see it.

**Comment by DocMAX** [comment]
http://www.filedropper.com/logcat

**Comment by DocMAX** [comment]
http://pastebin.com/1x3F8W4e

**Comment by Kra1o5** [comment]
Thanks, We check into it.

**Comment by Kra1o5** [comment]
No errors found, can you give us dmesg file?

**Comment by DocMAX** [comment]
http://pastebin.com/X46477QS

**Comment by cmorlok** [comment]
On my 3GB/32GB, /firmware is mounted correctly, but I see a lot of those messages in dmesg:

```
<6>[    5.888800] pil-q6v5-mss 4080000.qcom,mss: modem: loading from 0x86800000 to 0x8b800000
<6>[    5.896071] pil-q6v5-mss 4080000.qcom,mss: MBA: loading from 0x6f300000 to 0x6f400000
<3>[    5.936959] pil-q6v5-mss 4080000.qcom,mss: PBL returned unexpected status -285146880
<3>[    5.936968] RMB_MBA_IMAGE: 6f300000
<3>[    5.936973] RMB_PBL_STATUS: ef010100
<3>[    5.936978] RMB_MBA_COMMAND: 00000000
<3>[    5.936982] RMB_MBA_STATUS: 00000000
<3>[    5.936987] RMB_PMI_META_DATA: 00000000
<3>[    5.936992] RMB_PMI_CODE_START: 00000000
<3>[    5.936997] RMB_PMI_CODE_LENGTH: 00000000
<3>[    5.937039] pil-q6v5-mss 4080000.qcom,mss: MBA boot failed.
<3>[    5.937323] pil-q6v5-mss 4080000.qcom,mss: modem: Invalid firmware metadata
<3>[    5.937367] M-Notify: General: 5
<3>[    5.937379] adsp-loader qcom,msm-adsp-loader.19: adsp_loader_do: pil get failed,
<3>[    5.937387] adsp-loader qcom,msm-adsp-loader.19: adsp_loader_do: Q6 image loading failed
<6>[    5.943490] binder: 215:215 transaction failed 29189, size 0-0
<3>[    5.948008] M-Notify: General: 7
```

Edit: the same error appears on DocMAX's dmesg. Mine is here: http://pastebin.com/VubJTbyZ

**Comment by Kra1o5** [comment]
Yeah, MBA not boot correctly.

We can fix this, I will give you a test ASAP.

Greetings

**Comment by DocMAX** [comment]
Thx a lot, i'm waiting

**Comment by Kra1o5** [comment]
@DocMAX @cmorlok ,

Here the test: https://s.basketbuild.com/dl/devs?dl=Kra1o5/bq/piccolo/Test/boot.img

Flash via TWRP or fastboot.

Greetings

**Comment by DocMAX** [comment]
I get 404 error...

**Comment by Kra1o5** [comment]
I get the correct url.

**Comment by DocMAX** [comment]
It really doesnt work. Tried different computers, different browsers...

https://s.basketbuild.com/uploads/devs/Kra1o5/bq/piccolo/Test+Zone/boot.img

We couldn't find what you were looking for.

**Comment by Kra1o5** [comment]
Basketbuild have some problems I will upload to other host.

**Comment by Kra1o5** [comment]
@DocMAX @cmorlok , 

https://s.basketbuild.com/dl/devs?dl=Kra1o5/bq/piccolo/Test/boot.img

**Comment by stucki** [comment]
Just start here: https://s.basketbuild.com/devs/Kra1o5/bq/piccolo/
then navigate to the "Test" subfolder.

**Comment by DocMAX** [comment]
Works now :-)
Checking SIM issue now

**Comment by DocMAX** [comment]
Looking good now :-) SIM seems to work!

**Comment by stucki** [comment]
Great! Awesome work, Alejandro!

**Comment by Kra1o5** [comment]
;) Probably I make new release today!

Please check when new build is up & comment here the result to close the issue.

Greetings

**Comment by Kra1o5** [comment]
@DocMAX @cmorlok ,

New build is out.

This should be fine now.

**Comment by cmorlok** [comment]
New build works fine. Both SIM cards detected and mobile data is working

**Comment by stucki** [comment]
There was a new fix for this committed today:
https://github.com/piccolo-dev/android_kernel_bq_piccolo/commit/520bf435926e4dc0d7ca50b13f3509e0ee45a73e

I have made a test build at request of @Kra1o5. It works fine on my phone but I only have the 2 GB model:
https://www.dropbox.com/sh/oytnmfnm9o5763i/AAA9ikVUK_oOEXldYciSCfQea?dl=0

Can someone with a 3 GB model check it please and report here if mobile data still works?

**Comment by Kra1o5** [comment]
I think @DocMAX have last release running fine with modem.

**Comment by cmorlok** [comment]
I can confirm that the latest release is working fine on the 3/32

**Comment by Kra1o5** [comment]
Thanks for the feedback @cmorlok .

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#2
