### ISSUE TITLE
New bootloader as of bq M5-3.2.2

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#20]
Hello,

is there currently a need to update anything from the last firmware (3.2.2) bq released to a M5 flashed originally with a 1.2.4 firmware? At least the bootloader?

Also, as I understand, the new bootloader is locked, but can be unlocked via fastboot. Do you know the reasons behind this move?

I have seen a post over at htcmania, but unfortunately my Spanish is very near to non-existent.

Could you explain, please?

Gracias :)

**Comment by piwats** [comment]
Managed to update.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#20
