### ISSUE TITLE
20151220: Compass/hall/sensors (screen rotation) not working

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#21]
Hello,

I just have updated to 20151220 and noticed that the compass and other sensors stopped working.

F.e. the compass in GPS status app and cpuz sensor data is not show anything.

Any clues?

**Comment by piwats** [comment]
When enabling the compass tile in the notification/status bar, and turning there the compass on, it gets stuck at "initializing..."

**Comment by piwats** [comment]
Rotation also does not work, obviously, since sensor related.

Users over a htcmania are experiencing it, too, if I correctly translate:

@htcmania: http://www.htcmania.com/showpost.php?p=21322823&postcount=876

and a confirmation from another user @htcmania: http://www.htcmania.com/showpost.php?p=21322853&postcount=877

**Comment by Kra1o5** [comment]
Yes, is already fixed on repos, I will release new build today.

Greetings

**Comment by piwats** [comment]
Thank you very much :)

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#21
