### ISSUE TITLE
WiFi sometimes cant turn ON

### ISSUE THREAD

**Issue by yuichristian** [piccolo-dev/android_device_bq_piccolo#23]
After reboot,why sometimes WiFi stuck. i must reboot again if i want use WiFi

**Comment by Kra1o5** [comment]
Fixed in cm-12.1-20151227-UNOFFICIAL-piccolo.zip.

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#23
