### ISSUE TITLE
Reboots

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#24]
With the latest cm-12.1-20151221-UNOFFICIAL-piccolo.zip build i got some "random" reboots.

Screen freezes for 2 seconds ... then the device restarts: 
- while in my newsfeed-reader (feedly) for a few minutes
- while in Chrome after 2-3 minutes
- while on charger and not on charger
- i could reproduce this multiple times
- while receiving a call for a few seconds
- i couldn't force it with offline-content-browsing (photos and videos) 
- i tried to logcat it, but it couldn't provoke it during adb logcat was running
- after adb logcat, i also could't provoke it any more – until the next reboot
- i didn't try to wifi-logcat (because i don't have much time at the moment)

i've got the black M5 with 16gb and 2gb ram; 

(right now i flashed back to cm-12.1-20151213-UNOFFICIAL-piccolo.zip, which runs without problems.)

Anyone else getting these reboots?

:-) AK

KEEP UP THAT AWESOME WORK!

**Comment by Findecil** [comment]
Same observations, reboot at random times, even when not doing anything (phone in the pocket). Could not find anything relevant with Catlog.

I now have downgraded my system to the stable version from 20151213.

**Comment by piwats** [comment]
Have you updated prior to installing 20151220/20151221 to bq's 3.2.2 firmware?

I had reboots, too. It is required to update to 3.2.2 first.

**Comment by Findecil** [comment]
I did not, I just pushed the update offered by the phone without checking if there was a firmware update available. I'll do it, thanks.

**Comment by akamkomputer** [comment]
I didn't update the firmware too. Will check it later!

:-) AK

**Comment by piwats** [comment]
you will need to unlock the bootloader, though.

get the bootloader (fastboot mode) running, use then
fasboot oem unlock-go
to unlock it

**Comment by Cross0x0** [comment]
Same here, I didn't tried to update the firmware because I don't want to loose all my data yet.

**Comment by piwats** [comment]
Backup your data via twrp to a SD card and restore it later. I did so. Without any problems.

**Comment by akamkomputer** [comment]
What part of the firmware do i have to install? or the whole thing?
:-) AK

**Comment by piwats** [comment]
You have to install the whole firmware, boot it up, unlock the developer menu and turn off there an OEM lock off, too.

**Comment by Kra1o5** [comment]
Yes if you have 5.0.2 firmware as base you probably get reboots is a confirmed issue due to new kernel changes.

To fix this you need to have 5.1.1 firmware as base.

Greetings

**Comment by andresako** [comment]
One more here with the same problem :(
How can i downgrade it?
 I need to format all my device? =/

My dev:
m5 3Gb 64.
firmware base : 5.1.1

Upd. Data saved via twrp, how can I downgrade it now? =) 

_That need to be the first on everything without read....._

**Comment by Kra1o5** [comment]
You can flash old version from here: https://s.basketbuild.com/devs/Kra1o5/bq/piccolo it doesnt wipe any data.

Greetings

**Comment by andresako** [comment]
ok done, thanks!

**Comment by Findecil** [comment]
I upgraded the firmware to 3.2.2 (5.1.1), reinstalled CM and restored the data backup from TWRP.

I had to do it twice, because the first time I must have missed something as the accelerometer stopped working correctly. The second time seems to have worked as intended.

**Comment by akamkomputer** [comment]
Ok, that really went bad. 

I flashed all the partitions from the .bat file ... in osx. unfortunately i did't know immediately that rem means a comment.
so i did: fastboot flash partition gpt_both0.bin
and all the rest, but not more rem-lines.

After that the system booted fine and i had no more wifi / sim.

So I thought that section must be for the modemst1 and modest2 that i probably erased:

rem fastboot flash sec sec.dat
rem fastboot adb reboot bootloader fsg fs_image.tar.gz.mbn.img
rem fastboot flash modemst1 dummy.bin
rem fastboot flash modemst2 dummy.bin

i couldn't flash anything and i had to unlock the bootloader first. (dev-menu -> OEM unlock) 
fastboot oem unlock-go

then i continued with;
fastboot flash sec sec.dat

fastboot adb reboot bootloader fsg fs_image.tar.gz.mbn.img
didn't work obviously so i did a: 
fastboot reboot bootloader

Suddenly i got a linux-penguin in the middle of the screen. The bootloader was locked again. 
And it only restarts to the bootloader-screen.

fastboot oem unlock-go 
gives me 
FAILED (remote: oem unlock is not allowed)

i can't flash anything. 
DID I BRICK IT COMPLETELY? 

:-( AK

**Comment by Kra1o5** [comment]
Never flash partition init on bat with fastboot rem.

Contact with the technical service.

**Comment by akamkomputer** [comment]
I also think now the technical service will be my only hope. Then it'll be a christmas without a phone... 
:-/ AK

**Comment by Kra1o5** [comment]
Yeah, really bad luck :/

**Comment by akamkomputer** [comment]
What ist that sec.dat part ... just for my understanding?

**Comment by Kra1o5** [comment]
Not sure, sorry

**Comment by piwats** [comment]
@Kra1o5 

Could you put this in the wiki, so people won't destroy even more phones, when they are flashing under unixes?

```
#!/bin/bash
adb reboot bootloader
fastboot flash aboot emmc_appsboot.mbn
fastboot flash abootbak emmc_appsboot.mbn
fastboot erase DDR
fastboot flash sbl1 sbl1.mbn
fastboot flash sbl1bak sbl1.mbn
fastboot flash tz tz.mbn
fastboot flash tzbak tz.mbn
fastboot flash hyp hyp.mbn
fastboot flash hypbak hyp.mbn
fastboot flash rpm rpm.mbn
fastboot flash rpmbak rpm.mbn
fastboot flash modem NON-HLOS.bin
fastboot flash cache cache.img
fastboot erase splash
fastboot flash splash splash.img
fastboot flash system system.img
fastboot flash recovery recovery.img
fastboot flash userdata userdata.img
fastboot flash boot boot.img
fastboot erase config
fastboot erase devinfo
fastboot reboot
```

**Comment by Beule70** [comment]
I have downgraded my system to the stable version from 20151213 too.

How can i update the firmware to 3.2.2 (5.1.1) ? CM already running with Base Version is 5.1.1.

Hardware M5 - 3Gb 64.
firmware base : 5.1.1

All Version greater 20151213 makes random reboots!!! What can i do? How to install firmware to 3.2.2 (5.1.1) to get versions greater 20151213 works without reboots?

**Comment by antonioborondo** [comment]
I have the same question than @Beule70: what's the process to flash the phone with the Firmware 3.2.2? Should we download it from here http://www.mibqyyo.com/en-download/categorias/aquaris-m5/ and install it using TWRP?

**Comment by Kra1o5** [comment]
Hi @antonioborondo ,

It cant be flashed via TWRP,

You can use this tutorial (On spanish): http://www.htcmania.com/showpost.php?p=21274180&postcount=1

Greetings

**Comment by antonioborondo** [comment]
Thank you very much for the info @Kra1o5! The whole process seems to be a bit tricky! I hope not to brake my phone! :smile: 

EDITED: @Kra1o5, I followed the steps on your link and right now I have installed the 12.1-20160113-UNOFFICIAL-piccolo version. It works perfect. Thank you very much for your work!!! :+1:

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#24
