### ISSUE TITLE
No mp3 possible for clock alarm

### ISSUE THREAD

**Issue by DerSaxxe** [piccolo-dev/android_device_bq_piccolo#26]
In versions prior 20.12. there was no problem choosing mp3 as alarm. Now only ogg is possible.
Many thanks

**Comment by Kra1o5** [comment]
Hi @SIRSteiner,

Yeah, https://github.com/CyanogenMod/android_packages_apps_DeskClock/commit/60d907dd2e13350b20d9883b2a55e68f5566ce73

CM add support for OGG files & probably breaks the other formats.

**Comment by DerSaxxe** [comment]
Hello! I think this problem needs small changes because if I rename a MP3 to OGG (no convert) I can use it as alarm and it is playing

**Comment by Kra1o5** [comment]
Hi @ SIRSteiner, 

I will check it for next release (not today release).

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#26
