### ISSUE TITLE
No HDR Camera Mode available - App is crashing

### ISSUE THREAD

**Issue by andy-de** [piccolo-dev/android_device_bq_piccolo#27]
When taking a picture with enabled HDR mode the app is crashing.
While using the Google Camera App the app crashes and shows "can't connect to camera".
By using the Cyanogenmod Camera App the app does NOT crash, but there is no difference if the picture was taken with or without HDR.
CM Version: cm-12.1-20151227-UNOFFICIAL-piccolo

Seems the issue is related to the versions as of 20151220 (based on Stock 5.1.1?). Version 20151213 is working fine.

Logcat and Tombstone attached:

[Logcat.txt](https://github.com/piccolo-dev/android_device_bq_piccolo/files/77600/Logcat.txt)

[tombstone_07.txt](https://github.com/piccolo-dev/android_device_bq_piccolo/files/77601/tombstone_07.txt)

**Comment by DerSaxxe** [comment]
Same here and Open Camera takes no pictures in HDR mode.

**Comment by hobbypunk90** [comment]
I have the same problem

**Comment by Kra1o5** [comment]
Hi guys,

Is a libs problems, when it get fixed on stock it will be on CM too.

Greetings

**Comment by DerSaxxe** [comment]
Hi! I don't know why, but with the lastest build (20160113) HDR mode is working with Open Camera.

**Comment by Kra1o5** [comment]
Hi  @SIRSteiner ,

Its fixed for all cameras.

Greetings

**Comment by andy-de** [comment]
@Kra1o5 
HDR works fine (eg Google Camera) but not with the CyanogenMod Camera App. By using the Cyanogenmod Camera App there is still no difference if the picture was taken with or without HDR. 
Thank you for your awesome work.  :)

**Comment by Kra1o5** [comment]
Hi @andy-de ,

Yes, but is more one app problem than device.

**Comment by andy-de** [comment]
Ok, thank you. I thought it might be interesting. ;)

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#27
