### ISSUE TITLE
Flashlight does not work

### ISSUE THREAD

**Issue by cmorlok** [piccolo-dev/android_device_bq_piccolo#28]
The flashlight QS tile is inactive. Seems like the system doesn't know about the capabilities.

**Comment by piwats** [comment]
On cm-13.0-20160120 the behaviour seems to be the same. I noticed the tile when I was changing the tiles, but since the torch tile is somehow gone to where I have no idea about.

**Comment by cmorlok** [comment]
I am still investigating this. It seems to be an upstream issue. The flashlight was working for some time, but it suddenly disappeared again. Our camera reports the available features correctly, but it implements the oldest available interface (Camera1/HAL1). Maybe it's a bug in the Camer2->Camera1 wrapper.

**Comment by stucki** [comment]
Btw. I'm using Runtastic Sleep Better which also provides a flashlight when the alarm is on, and it works fine there.

**Comment by cmorlok** [comment]
The flashlight itself is working fine. And the camera API correctly returns that is has a flashlight. The problem is somewhere on the way between the Flashlight QS tile and the camera: there is a function that tries to find out if the camera has a flashlight. If this function returns true, the tile is shown, otherwise it doesn't appear. For whatever reason this function returns false. And I don't know if this is the case for all devices with HAL1 or if it's just for us. I have seen in some device repos that they override the system flashlight handling completely. Maybe this is a workaround, but I would prefer to fix it upstream (if it is an upstream bug).

**Comment by cmorlok** [comment]
Fixed in build 2016/01/24.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#28
