### ISSUE TITLE
Preferred SIM for Cellular data switches between SIM 1 and 2

### ISSUE THREAD

**Issue by cmorlok** [piccolo-dev/android_device_bq_piccolo#29]
After reboots, mobile data is sometimes automatically set to SIM 2

**Comment by stucki** [comment]
I can confirm this. It may be fixed since yesterday, see http://review.cyanogenmod.org/#/c/128480
However, I'm unable to make a new build since then (still checking the reason...).

**Comment by cmorlok** [comment]
128480 fixes something else.

This bug has been introduced by http://review.cyanogenmod.org/#/c/121239
For details, see my comment there.

I have reverted this change for build 20160117, so it should temporarily be fixed now.

**Comment by cmorlok** [comment]
Waiting for the fix http://review.cyanogenmod.org/#/c/130332 to be merged.

**Comment by cmorlok** [comment]
Has been merged on Feb 1st, will be fixed in next build.

**Comment by Kra1o5** [comment]
We now release weekly builds.

Greetings

**Comment by cmorlok** [comment]
Fixed in 2016/02/07

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#29
