### ISSUE TITLE
ChangeLog does not load

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_device_bq_piccolo#3]
The ChangeLog display in CyanogenMod-Updater does not seem to work. When I click on a release, the popup opens and loads forever. I reported this already to @Kra1o5 who cannot reproduce the issue, while for me it is reproducable. How about others?

How to reproduce:
Settings => About the phone => CyanogenMod-Updates => Click on any release

The expected output can be found at https://github.com/piccolo-dev/CHANGES/tree/master/_builds/piccolo/nightly

**Comment by Kra1o5** [comment]
Its works for me: https://dl.dropboxusercontent.com/u/27852275/Screenshot_2015-09-20-15-37-46.png

**Comment by stucki** [comment]
I believe you that it works for you :-) Still want to know if I'm alone with this problem or not.

Btw. nevertheless, device/bq/vegetalte/ and device/xiaomi/ do not belong to this changelog.

**Comment by Kra1o5** [comment]
Yes, includes vegetalte & armani  because is on my local_manifest, I support both.

Greetings

**Comment by 205er** [comment]
It does definitely not work for build 20151004 and 20150922! --> loading forever.

**Comment by Kra1o5** [comment]
Well, I have it working.

Maybe ISP problems?

**Comment by stucki** [comment]
It didn't work using mobile data as well as wireless lan. Today however, it's working fine here. Need to try again at home...

**Comment by bonanzabike** [comment]
I had this issue on my Samsung Galaxy S4 Mini with CM13 Nightlys and I discovered that it did only work for newer, not yet installed, but downloaded versions.
So whenever there was a new update found, I could read the changelog by tapping and holding at the newest version, but after the update it didn't work anymore. When I wanted to open it by pressing the newest, installed version, it said "no changelog available" and when I wanted to open it by pressing the older version it loaded forever.

I guess that CM "compares" the version you tap on with the version installed, so it might be the point, that there isn't any changelog from the installed version to an older version, but only to newer versions.

**Comment by stucki** [comment]
This works now.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#3
