### ISSUE TITLE
Preferred network type can't be changed

### ISSUE THREAD

**Issue by cmorlok** [piccolo-dev/android_device_bq_piccolo#30]
It's always 4G on SIM 1 and 2G on SIM 2, no matter what has been selected in settings.

**Comment by cmorlok** [comment]
Fixed.

**Comment by cmorlok** [comment]
If network type still can't be changed, it might be because of #35

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#30
