### ISSUE TITLE
Bluetooth power consumption is calculated wrong

### ISSUE THREAD

**Issue by cmorlok** [piccolo-dev/android_device_bq_piccolo#31]
![screenshot_20151214-085638](https://cloud.githubusercontent.com/assets/1296377/12247954/bd5c67d2-b8b6-11e5-9619-f3d66a70abfa.png)
![screenshot_20151214-085644](https://cloud.githubusercontent.com/assets/1296377/12247955/bd76eaee-b8b6-11e5-8523-b14ccca01ee8.png)

**Comment by Kra1o5** [comment]
Yes, we need to set value in overlay to fix it.

**Comment by cmorlok** [comment]
Fixed.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#31
