### ISSUE TITLE
Roaming by default

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#34]
I dont know if it's a bug ... but it could get expensive (for somebody who travels often between switzerland and EU ;-)

Roaming on both SIM-cards was automatically set to „on“ after a clean install of CM13 (20150112) (install-langauge: English-US)

:-) AK

**Comment by cmorlok** [comment]
This has been fixed upstream: http://review.cyanogenmod.org/#/c/127943/

Will be fixed in the next build.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#34
