### ISSUE TITLE
Kernel DIAG_CHAR for radio debug & SnoopSnitch

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#36]
Hello,

would it be possible to enable DIAG_CHAR in the kernel, so one can use SnoopSnitch?

via https://opensource.srlabs.de/projects/snoopsnitch

This one has no priority at all.

Thanks in advance :)

**Comment by cmorlok** [comment]
This has been enabled right from the beginning:
https://github.com/piccolo-dev/android_kernel_bq_piccolo/blame/cm-12.1-test/arch/arm/configs/cyanogenmod_piccolo_defconfig#L1691
https://github.com/piccolo-dev/android_kernel_bq_piccolo/blame/cm-13.0-test/arch/arm/configs/cyanogenmod_piccolo_defconfig#L1692

Do you have any problems with the app?

**Comment by piwats** [comment]
That's great news.

I was not sure about whether it was actually enabled.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#36
