### ISSUE TITLE
cm-13: double tap activation not working

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#37]
With the first cm-13 build from 20th of January (cm-13-20160120), double tap to wake up is not working.

Logcat shows absolutely nothing, neither when I'm double taping on the display, no when I enable or disable double tap in the settings.

Double tap for standby is working, though.

dmesg is a source of fortune:

```
[    8.572114] type=1400 audit(2688159.009:5): avc: denied { execute_no_trans } for pid=272 comm="init" path="/system/bin/init.atmel_ts.sh" dev="mmcblk0p27" ino=259 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
```

**Comment by Kra1o5** [comment]
Already fixed.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#37
