### ISSUE TITLE
Download counter not working

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_device_bq_piccolo#4]
It seems to me like the download counter at https://s.basketbuild.com/devs/Kra1o5/bq/piccolo/ is totally wrong. I downloaded the 20150919 release so the counter should be at least 1 - although I think it should be at 10-20. I don't know the real numbers, but 0 is wrong for sure!

**Comment by Kra1o5** [comment]
Yes is normal behavior.

Basketbuild only count downloads make on website not direct download (OTA).

& is error of the host.

**Comment by stucki** [comment]
I understand that it's not your fault, however this should be fixed by the Basketbuild operators. It just looks bad if a release is only downloaded 3-4 times, even tough I'm sure that there are at least 30 people using the ROM... Is there a way to get in touch with the hoster?

**Comment by Kra1o5** [comment]
Yes, you can contact him here: support@basketbuild.com

Greetings

**Comment by stucki** [comment]
Asked them now, let's close the issue here.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#4
