### ISSUE TITLE
Adoptable storage broken after upgrade

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#40]
I upgraded from CM13(160114) to CM13(160117) ...

After the Apps-initialising the SIM-pin-screen i got a lot of error-messages, that various apps were closed.
And one message, that my SD-card cannot be read. 
I previously formatted that as „internal storage“ (not as „portable“).
I can imagine that the FCs had something to do with the app-data stored on the SD-card. The system was not usable due to the many FCs.

After a reboot i always ended up on a screen with only the notification-drop-down working (showing the SD-card-error) but nothing else. Also no more error messages and i was not able to access something else (like the settings-screen). The SIM-card-pin-screen also didn't show up any more.

Downgrading to CM13(160114) fixed all problems.

:-) AK

p.s. btw. i still have the Video-Camera-FC on 160114. Was that fixed again in 160117?

**Comment by cmorlok** [comment]
Can you provide us some logcats?

**Comment by akamkomputer** [comment]
sorry, i'm already on 160114 again ... i would have to reinstall 160117

**Comment by akamkomputer** [comment]
Does anybody use the SD-card-internal-storage feature? or even upgraded succesfully (to 20160117 or later?)

**Comment by akamkomputer** [comment]
I formatted the SD-card to portable before upgrading to 160120... then everything worked out fine.
:-) AK

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#40
