### ISSUE TITLE
Double tap activation not working when charging

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#42]
When the phone is charging and the charging cable is connected, double tap to activate is **not** working/responding.

When not charging and the cable is disconnected, double tap is working as it should.

**Comment by piwats** [comment]
Does only happen when on external charger.

When connected to a laptop, it seems to work though.

**Comment by piwats** [comment]
Seems to not work only if charging, e.g. <95%.

**Comment by Kra1o5** [comment]
We can take a look into it.

@eloimuns can test it?

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#42
