### ISSUE TITLE
GPS location icon

### ISSUE THREAD

**Issue by 1tft** [piccolo-dev/android_device_bq_piccolo#43]
Hello, first I want to say a big respect for this CM13 Rom for Aquaris M5.
I'm really enjoying this stable and smooth ROM. Thank you! Is there any way to donate via bitcoin because I don't want to make evil Paypal more profit?!

One question to this ROM: With Android 4.x / CM 11.x location icon was blinking/flashing when searching for a fix and only was permanent displayed when device had a GPS fix.
At the moment location icon is permanently displayed when device begins to search for location.
I found this information very useful when device is searching for a fix and thats why I want to ask, is this a CM-, Android- or device specific problem?
Is there any way to switch to the old behaviour?

**Comment by piwats** [comment]
cm-13 is yet not fully complete in comparison with cm-12.1.

If you have noticed, there are no indicators of downloading on the wifi and sim icons, too.

Please be patient. Cyanogen has not released cm-13 yet. At this point it is still experimental and even lacks some of the futures common, available and very appreciated in cm-12.

**Comment by Kra1o5** [comment]
Yes, CM13.0 is WIP upstream.

**Comment by 1tft** [comment]
Thank you for this information. @Kra1o5 do you have a bitcoin address so that I can say thx for this great ROM?

**Comment by Kra1o5** [comment]
@1tft , not but dont worry I do this for fun its a hobby.

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#43
