### ISSUE TITLE
Impossible to remove Heads up notifications

### ISSUE THREAD

**Issue by airesdp** [piccolo-dev/android_device_bq_piccolo#44]
It seems to work, but when you recieve three continued notifications, the head up appears.
I tested with third-party applications and the same thing happens. No way to fix it.

---

_No se pueden desactivar las notificaciones Heads up. Parece que funciona, pero en cuanto llegan tres notificaciones seguidas vuelve a aparecer. Ni siquiera con otras aplicaciones he logrado que funcione._

**Comment by Kra1o5** [comment]
Hi @airesdp ,

Thanks for the feedback, can you provide us one logcat?

**Comment by airesdp** [comment]
I'll find how to do that and tomorrow morning i'll do it. I've asked to other users about the problem and the same happen to them.

Thank you for your job!!

**Comment by airesdp** [comment]
I tried the new build and the bug continues.

Here is the logcat.
[2016-02-01-15-57-37aaa.txt](https://github.com/piccolo-dev/android_device_bq_piccolo/files/112434/2016-02-01-15-57-37aaa.txt)

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#44
