### ISSUE TITLE
USB mode settings are not saved

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#46]
When connecting to a laptop, for file transfer one has to set the mode to MTP every time a connection is made.

It seems that CM13 does not yet save this setting.

**Comment by Kra1o5** [comment]
Yeah, now the default behavior is charger.

**Comment by piwats** [comment]
Is it intentional or a bug then?

**Comment by Kra1o5** [comment]
Now We dont set default to mtp.

**Comment by piwats** [comment]
This is indeed intentional and a major change in 6.0.

No bug at all.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#46
