### ISSUE TITLE
Selecting network doesn't work for SIM 2

### ISSUE THREAD

**Issue by starvoid** [piccolo-dev/android_device_bq_piccolo#48]
When I try to change the network mode of the SIM2 from 2G to 3G or LTE, it seems no has effect. The same interface works fine for SIM1.

I'm using the 7/1/2016 image.

Thanks for your effort and good work.

Please, find attach the logcat in that moment:

02-08 10:12:07.007  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:07.019  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:08.665   277   277 V WLAN_PSA: NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
02-08 10:12:08.665   277   277 V WLAN_PSA: NL MSG, PID: 277
02-08 10:12:10.023  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:10.024   277   277 V WLAN_PSA: NL MSG, len[4072], NL type[0x1C] WNI type[0x5900] len[53263]
02-08 10:12:10.024   277   277 V WLAN_PSA: NL MSG, PID: 277
02-08 10:12:10.036  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:10.622   267  1626 D audio_hw_primary: start_output_stream: enter: stream(0xb892e730)usecase(1: low-latency-playback) devices(0x2)
02-08 10:12:10.622   267  1626 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
02-08 10:12:10.622   267  1626 W msm8916_platform: Codec backend bitwidth 16, samplerate 48000
02-08 10:12:10.622   267  1626 D hardware_info: hw_info_append_hw_type : device_name = speaker
02-08 10:12:10.623   267  1626 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
02-08 10:12:10.652   267  1626 W audio_hw_utils: audio_extn_utils_update_stream_app_type_cfg: App type could not be selected. Falling back to default
02-08 10:12:10.652   267  1626 I audio_hw_primary: select_devices Selected apptype: 69936
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 14, path =  0
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_asm_topology
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_adm_topology
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_audtable
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_audvoltable
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_afe_cal
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 14 path = 0
02-08 10:12:10.652   267  1626 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
02-08 10:12:10.655   267  1626 I audio_hw_utils: audio_extn_utils_send_app_type_cfg app_type 69936, acdb_dev_id 14, sample_rate 48000
02-08 10:12:10.655   267  1626 D audio_hw_primary: enable_audio_route: apply mixer and update path: low-latency-playback
02-08 10:12:10.660   267  1626 D audio_hw_primary: select_devices: done
02-08 10:12:10.660  2774  2774 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
02-08 10:12:10.663   959  2335 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@db18ec1 attribute=null, token = android.os.BinderProxy@f4e6f8d
02-08 10:12:10.665  2774  2774 D NetworkSettings: onPreferenceChange
02-08 10:12:10.665  2774  2774 D NetworkSettings: buttonNetworkMode: 9
02-08 10:12:10.686  2774  2774 D NetworkSettings: isWorldMode=false
02-08 10:12:10.701  2774  2774 D NetworkSettings: handleSetPreferredNetworkTypeResponse: exception in setting network mode.
02-08 10:12:10.726  2774  2774 D NetworkSettings: updatePreferredNetworkUIFromDb: settingsNetworkMode = 1
02-08 10:12:10.751   261   261 I MSM-irqbalance: Decided to move IRQ240 from CPU5 to CPU6
02-08 10:12:10.762   267  1626 D audio_hw_primary: start_output_stream: exit
02-08 10:12:13.042  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:13.056  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:13.675   277   277 V WLAN_PSA: NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
02-08 10:12:13.675   277   277 V WLAN_PSA: NL MSG, PID: 277
02-08 10:12:13.919   267  1626 D audio_hw_primary: out_standby: enter: stream (0xb892e730) usecase(1: low-latency-playback)
02-08 10:12:13.960   267  1626 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
02-08 10:12:13.962   267  1626 D hardware_info: hw_info_append_hw_type : device_name = speaker
02-08 10:12:13.962   267  1626 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
02-08 10:12:15.750   261   261 I MSM-irqbalance: Decided to move IRQ174 from CPU5 to CPU6
02-08 10:12:16.061  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:16.074  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:16.074   277   277 V WLAN_PSA: NL MSG, len[4085], NL type[0x1C] WNI type[0x5900] len[56591]
02-08 10:12:16.074   277   277 V WLAN_PSA: NL MSG, PID: 277
02-08 10:12:18.686   277   277 V WLAN_PSA: NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
02-08 10:12:18.686   277   277 V WLAN_PSA: NL MSG, PID: 277
02-08 10:12:19.080  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:19.090  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:22.096  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-08 10:12:22.108  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
02-08 10:12:22.263  2332  2332 D wpa_supplicant: wlan0: Control interface command 'SCAN TYPE=ONLY'
02-08 10:12:22.263  2332  2332 D wpa_supplicant: wlan0: Setting scan request: 0.000000 sec
02-08 10:12:22.263  2332  2332 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=3
02-08 10:12:22.263  2332  2332 D wpa_supplicant: wlan0: Starting AP scan for wildcard SSID
02-08 10:12:22.263  2332  2332 D wpa_supplicant: wlan0: Add radio work 'scan'@0xb79128a0
02-08 10:12:22.263  2332  2332 D wpa_supplicant: wlan0: First radio work item in the queue - schedule start immediately
02-08 10:12:22.264  2332  2332 D wpa_supplicant: wlan0: Starting radio work 'scan'@0xb79128a0 after 0.000064 second wait
02-08 10:12:22.264  2332  2332 D wpa_supplicant: wlan0: nl80211: scan request
02-08 10:12:22.264  2332  2332 D wpa_supplicant: nl80211: Scan SSID - hexdump(len=0): [NULL]
02-08 10:12:22.264  2332  2332 D wpa_supplicant: nl80211: Scan extra IEs - hexdump(len=7): 7f 05 00 00 0a 02 01
02-08 10:12:22.264  2332  2332 D wpa_supplicant: Scan requested (ret=0) - scan timeout 30 seconds
02-08 10:12:22.264  2332  2332 D wpa_supplicant: nl80211: Event message available
02-08 10:12:22.264  2332  2332 D wpa_supplicant: nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan0
02-08 10:12:22.264  2332  2332 D wpa_supplicant: wlan0: nl80211: Scan trigger
02-08 10:12:22.264  2332  2332 D wpa_supplicant: wlan0: Event SCAN_STARTED (47) received
02-08 10:12:22.264  2332  2332 D wpa_supplicant: wlan0: Own scan request started a scan in 0.000144 seconds
02-08 10:12:22.264  2332  2332 D wpa_supplicant: CTRL-DEBUG: ctrl_sock-sendmsg: sock=11 sndbuf=163840 outq=448 send_len=24
02-08 10:12:22.264  2332  2332 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_959-2\x00
02-08 10:12:22.265   277   277 V WLAN_PSA: NL MSG, len[914], NL type[0x11] WNI type[0x5050] len[894]

**Comment by starvoid** [comment]
duplicate issue

**Comment by dkati** [comment]
so what was the solution on this :/ ?

**Comment by piwats** [comment]
You first choose the mode on SIM1, then you can choose the mode on SIM2.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#48
