### ISSUE TITLE
Random reboots 

### ISSUE THREAD

**Issue by andresako** [piccolo-dev/android_device_bq_piccolo#49]
Yesterday I try to upgrade my M5 to cm13 with a very bad results. 

At first, reboots after 5 min, I try to find the last_kmsg without luck. 

After all day, I decided to downgrade to a stable cm12, but I still having this random reboots, maybe after 3 or 4 hours, but I cant let it like this. 

I want to help you to fix it, what can I do? 

Ps. Last_kmsg still without appear

**Comment by cmorlok** [comment]
Have you upgraded to the latest ROM from BQ (at least 3.2.2) before
installing CM?

**Comment by andresako** [comment]
I thought so, I was using the cm12 at V, 20151213 without problems  since this summer.
I need to install the official bq rom before cm13?

**Comment by cmorlok** [comment]
You need to install the latest BQ ROM for any CM after 20151220.

**Comment by andresako** [comment]
Damn!
I'm on it right now  TY!

ps. to do that... ? ''^.^

**Comment by cmorlok** [comment]
Be aware that you have to unlock the bootloader after installing the latest
BQ ROM. Normally, this will wipe the phone completely (including internal
SD). There are some instructions on the web about how to avoid that.

**Comment by andresako** [comment]
I'm ready to start with all of that but I have a question, twrp 2.8.7 it's fine? Or I need 3.0? And finally, to install the twrp.img, how can I do that? 
Thanks a lot

**Comment by andresako** [comment]
ok so, upgrading my status:

Now I have the last stock rom installed.
Reboots errors seems to have solved.

My problem now is I can't install the TWRP,
i'm trying with TWRP 3.0.img

adb reboot bootloader  //enter on fastboot
fastboot flash recovery twrp.img  //cmd close normally (?)
fastboot reboot  //reboot and still the stock recovery

What i'm doing wrong?
Thank's for the help 

---

edit: 
TWRP installed, i don't see that "push vol+ when install trwp.img"  my bad.
i'm flashing cm13 now, i'll keep reporting

---

edit2:
CM13 installed and think that it gone well
hope that reboots don't come back :)

Thanks for all
 and think that i can close now

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#49
