### ISSUE TITLE
Double tap to wake not working in 13.0-20160214

### ISSUE THREAD

**Issue by 1tft** [piccolo-dev/android_device_bq_piccolo#50]
Helle, just upgraded from 13.0-20160207 to 13.0-20160214 and double-tap to wake not working any longer.
Switched settings and rebooted phone but problem still exists.
Tap to sleep is still working.

**Comment by piwats** [comment]
Same here.

@Kra1o5: Is an update to the 3.2.7 bootloader needed?

**Comment by ghost** [comment]
Same. I can lock the phone by hitting twice in the status bar, but I cannot wake it double-tapping the screen.

**Comment by Kra1o5** [comment]
Hi,

Will be fixed in 13.0-20160215 build.

Greetings

**Comment by 1tft** [comment]
It's fixed. Thank you very much!
Issue can be closed.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#50
