### ISSUE TITLE
Sound Recorder can not save recordings to SD card

### ISSUE THREAD

**Issue by 1tft** [piccolo-dev/android_device_bq_piccolo#51]
Don't know if it is a CM13 problem or a piccolo one.
Just wanted to mention that if you choose "SD card" as Storage location in the the SoundRecorder settings and start recording you get the error message "Unfortunaely, Sound Recorder has stopped"
Everything is working fine with setting Storage location -> Phone storage.
Affected 13.0-20160214 and former 13.0-xxxxxxxx versions.

**Comment by cmorlok** [comment]
Logcats, please.

**Comment by 1tft** [comment]
W/PackageManager( 787): Not granting permission android.permission.WRITE_MEDIA_STORAGE to package com.android.soundrecorder (protectionLevel=18 flags=0x3008be45
W/PackageManager( 787): Not granting permission android.permission.CAPTURE_AUDIO_OUTPUT to package com.android.soundrecorder (protectionLevel=18 flags=0x3008be45

**Comment by cmorlok** [comment]
I can reproduce the issue, there are no open upstream commits.

**Comment by 1tft** [comment]
Hello, want to tell some more information about the latest situation I explored. Maybe someone is also faced with this problem.

2 bq M5 phones

First phone: Firmware 3.2.8
CM13.0-20160306 installed, but updated from earlier CM13 versions (only with dalvik and cache wipe).

Sound recorder says "can't access SD card" (no crash anymore!), but all neccessary rights are given to this app. Also I deleted app data etc.
Changed SD card with second device, no success.

---

Second phone: Firmware 3.2.9
CM13.0-20160306 (absolut fresh installation)
Sound recorder can store recording on SD card.
Changed SD card with first device, everything still works.

**Comment by Kra1o5** [comment]
Hi @1tft ,

Same behavior for me.

One question,

Second SD card have the format of MM ?

**Comment by 1tft** [comment]
MM?
Both SD cards are used as external (portable photo media). One SD 8GB with Fat32, second one 128GB with exFat.

**Comment by cmorlok** [comment]
It's still an open upstream issue (see comments on http://review.cyanogenmod.org/#/c/133098/ ). Seems like it has very low priority, no one cares about it.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#51
