### ISSUE TITLE
Hall sensor lockscreen feature

### ISSUE THREAD

**Issue by ghost** [piccolo-dev/android_device_bq_piccolo#52]
Is currently supported the feature that wakes the screen when using the official cover? I mean, when the hall sensor detect a magnetic field from the magnet inside the cover while you are closing and opening it lo unlock the phone. It's a pretty useful feature that the official ROM from BQ has.

**Comment by cmorlok** [comment]
Is this a question or a bug report? Hall sensor should work in CM12.1 and CM13.0.

**Comment by ghost** [comment]
If it's supposed to work then it's a bug report. When I previously had the official ROM from BQ I could lock and wake the screen by closing and opening the official cover, like the Nexus 5 does. I just could be wrong but as far as I know the cover has a magnet that is detected by the hall sensor in order to lock and wake the screen.
Thanks for the help and sorry if I'm posting this in a wrong place.

**Comment by cmorlok** [comment]
This is the correct place for reporting bugs.

Which build of CM do you have installed?

**Comment by ghost** [comment]
13.0-20160215-UNOFFICIAL-piccolo in my BQ M5

**Comment by Kra1o5** [comment]
Hi @PabloGPZ @cmorlok ,

Support is there: 

https://github.com/piccolo-dev/android_kernel_bq_piccolo/blob/cm-13.0-test/arch/arm/configs/cyanogenmod_piccolo_defconfig#L1629

https://github.com/piccolo-dev/android_device_bq_piccolo/blob/cm-13.0-test/overlay/frameworks/base/core/res/res/values/config.xml#L120

But I cant test if this works or not because I dont have this case.

Greetings

**Comment by cmorlok** [comment]
@ https://github.com/PabloGPZPabloGPZ https://github.com/PabloGPZ can
you send us a picture where the magnet is located in the case? I don't have
one either, but it should work with any other magnet as well.

**Comment by ghost** [comment]
I've tried with another magnet from google's cardboard VR (they work fine with the app so I know the magnetic sensor is working) and it doesn't do anything, I've also tried to read the information from the magnetic sensor and when I put close the magnet and it reads it. The magnet from the cover is also attracting iron,so it's there. I don't know where's the problem.

The magnet is inside the red circle.

![picture 1](https://cloud.githubusercontent.com/assets/17255079/13119147/da3a5356-d5a7-11e5-97d8-49216bd6b7fe.jpg)

**Comment by Kra1o5** [comment]
Hi @PabloGPZ ,

Sorry for the delay.

@eloimuns , @cmorlok Can you test it?

Regards

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#52
