### ISSUE TITLE
Problems with Bluetooth

### ISSUE THREAD

**Issue by fermaxando** [piccolo-dev/android_device_bq_piccolo#54]
When i will going to share my conexion from bluetooth by PAN Network (Wifi's zone section), the computer doesn't connect y was try with 3 computers with differents bluetooth.

**Comment by Kra1o5** [comment]
Hi,

Please specific version of CM.

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#54
