### ISSUE TITLE
SIM not available on first boot after update

### ISSUE THREAD

**Issue by cmorlok** [piccolo-dev/android_device_bq_piccolo#55]
Directly after an update (rebooting directly from TWRP), SIMs are sometimes not available. Everything is fine after rebooting.

**Comment by Kra1o5** [comment]
Really weird, maybe upstream issue?

For now I cant reproduce it, @eloimuns you did?

**Comment by cmorlok** [comment]
It's not really reproduceable, I get it on about 1 of 10 updates. On the german forum one guy reported the issue as well after an OTA update. It might be a timing issue.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#55
