### ISSUE TITLE
Incorrect labeling of button backlight control CM-13.0

### ISSUE THREAD

**Issue by DerSaxxe** [piccolo-dev/android_device_bq_piccolo#56]
To set auto-off button backlight to "never" (backlight always on) you have to set "35 s" (right edge of the slider). And if you set it to "never" (left edge of the slider) backlight will be on only 1 s.

**Comment by Kra1o5** [comment]
Hi @SIRSteiner ,

Yeah, because you set never but it set 1s.

Its a CM upstream issue not device specific.

Greetings

**Comment by DerSaxxe** [comment]
This seems to be fixed.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#56
