### ISSUE TITLE
Battery status and LED "freeze" after loading

### ISSUE THREAD

**Issue by bonanzabike** [piccolo-dev/android_device_bq_piccolo#59]
After loading the battery overnight and unplugging the cable next morning the status LED still remains shining green and the battery level remains at 100%, even if I use the phone for hours.
The monitoring of the battery level in the battery settings section stopped in the middle of the night, shortly after it reached the 100%.

Rebooting solved the problem, but another user told me he had this bug sporadically, too, until one day it disappeared.

**Comment by bonanzabike** [comment]
oh, I forgot to tell that I was using cm-13.0-20160228 build from https://s.basketbuild.com/devs/eloimuns/bq/piccolo/

**Comment by Kra1o5** [comment]
Really weird @bonanzabike I will try to reproduce it.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#59
