### ISSUE TITLE
Bluetooth and USB tethering not working

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_device_bq_piccolo#6]
It seems like bluetooth and USB tethering are both not working. WLAN tethering does work. Can anyone confirm this behaviour?

**Comment by Kra1o5** [comment]
Well, for USB tethering you cant have one option selected (MTP,PTP, Charge only) need to be in "USB Install Mode" .

**Comment by stucki** [comment]
Well, it worked fine on other models so far. What could be the problem?
I'm not even sure if it's the same problem for bluetooth and USB - maybe these problems are not related to each other...

**Comment by stucki** [comment]
I must add: The connection from my computer to the phone is established successfully, however I'm not getting any data. Need to investigate if the routing and firewall settings are correct...

**Comment by Kra1o5** [comment]
Yes, it works with USB without options selected (at least on my E5 4G) .

**Comment by stucki** [comment]
Really strange, it works now! It even works when using bluetooth tethering, and it even works after a reboot. :-)

I really tried many times before without success, so I assume it was fixed with the following step:

The setting you mentioned (no USB mode selected) was already present - so what I did was to enable each and disable it again.

This seems really weird - maybe someone else can try and confirm this solution? (In this case I would assume that there are some wrong default settings...)

**Comment by stucki** [comment]
Even better: Now it even works when I have MTP selected. Works with USB tethering & with bluetooth tethering. Really sounds to me like a wrong setting was the problem...

**Comment by Kra1o5** [comment]
Yes, I can test when get the device.

**Comment by stucki** [comment]
Thank you!

**Comment by stucki** [comment]
Hey I think this can be closed. In retrospective I don't really know if switching off and on was needed to fix it, however I cannot reproduce the problem anymore since then...

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#6
