### ISSUE TITLE
Alarm doesn't work when phone is off

### ISSUE THREAD

**Issue by bladimirsuareznuclear** [piccolo-dev/android_device_bq_piccolo#60]
This function works well in CM 12.1. I have updated to CM 13, and it is strange that before gapps was installed, alarm with phone off, works perfectly. After that I installed gapps, and it is when alarm with the phone off doesn't work.

**Comment by cmorlok** [comment]
You have to install gapps _before_ you boot the first time.

**Comment by bladimirsuareznuclear** [comment]
I did it too. Doesnt work.

**Comment by Kra1o5** [comment]
@eloimuns Can you try it please?

**Comment by Kra1o5** [comment]
@eloimuns report is working fine in his case.

**Comment by DerSaxxe** [comment]
Also tested and works fine. So maybe if nobody else have this problem and bladimirsuareznuclear also not with the latest build you should close this issue.

**Comment by Kra1o5** [comment]
@bladimirsuareznuclear, you can report it back with latest build?

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#60
