### ISSUE TITLE
Clock app is crashing at settings and alarm

### ISSUE THREAD

**Issue by DerSaxxe** [piccolo-dev/android_device_bq_piccolo#61]
If you click to open settings in the clock app it crashs. Also while alarm is ringing it crashs.

**Comment by Kra1o5** [comment]
Hi @SIRSteiner ,

You try to wipe app data?

Greetings

**Comment by DerSaxxe** [comment]
Inside Android clear data? Yes. But not all data in TWRP

**Comment by DerSaxxe** [comment]
Did also a wipe cache but no changes. I have also a M5 with CM13 and the build from last week, there is no problem with clock

**Comment by eloimuns** [comment]
It's a cyanogenmod problem

Will be repaired asap.

**Comment by Kra1o5** [comment]
Yes, @SIRSteiner you can use: https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=es

As workaround, we release a new build asap it get fixed.

Greetings

**Comment by DerSaxxe** [comment]
Thank you!

**Comment by Kra1o5** [comment]
Seems to be fixed upstream: https://github.com/CyanogenMod/android_frameworks_support/commit/9ac291bad6edb745d68aab9baf0465c3323d8e4e & will be fixed in todays build.

**Comment by DerSaxxe** [comment]
While ringing there is now no crash but if you want to open settings clock crashs

**Comment by Kra1o5** [comment]
Yes, its in the changelog but is upstream bug.

**Comment by DerSaxxe** [comment]
Here is the log maybe that helps more:

03-20 21:47:30.265 E/AndroidRuntime(6198): java.lang.RuntimeException: Unable to resume activity {com.android.deskclock/com.android.deskclock.SettingsActivity}: java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments

**Comment by DerSaxxe** [comment]
I found in the source strings.xml a (plurals) string named "auto_silence_summary" with a variable "%s" but in other languages there is only a single string with "%d".

I did a comment at https://jira.cyanogenmod.org/browse/NIGHTLIES-2671
Maybe this is the problem?

**Comment by Kra1o5** [comment]
Hi @SIRSteiner ,

Yes, the fix is review in progress here: http://review.cyanogenmod.org/#/c/137803/

So probably get merged soon & will be in next build.

**Comment by DerSaxxe** [comment]
Fixed with the latest build

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#61
