### ISSUE TITLE
Custom APN is ignored

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_device_bq_piccolo#62]
I'm trying to use the blau.de Tagesflat. This is a subscription which is activated by using a non-default APN.

After being online for a while, I notice that the APN was not used even though it was displayed like that in settings.

Can anyone confirm the behaviour? It is quite likely that the same problem occurs with other providers, too...

**Comment by Kra1o5** [comment]
Hi @stucki ,

Weird but can be the apn-conf file from cm.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#62
