### ISSUE TITLE
System freezes

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#63]
i recently updated from **cm-13.0-20160228** to **cm-13.0-20160313**.

Now i have random freezes, where only a forced restart (pressing the 3-buttons) of the phone helps.
I occurs most likely when switching when doing performance-intensive tasks ... switching and editing photos, browsing spotify, browsing, etc.

I'm still on firmware 3.2.2. – might this be a problem?
(cm-13.0-20160228 was just running fine.)

I logcatted, but couldn't see anything suspicious.

:-) AK

BTW: Thanks for that great work!

**Comment by akamkomputer** [comment]
And for updating the firmware to 3.2.9:
Can i just comment-out the lines:

```
fastboot flash system system.img
fastboot flash recovery recovery.img
fastboot flash userdata userdata.img
```

for not loosing my data, etc. (as i can't do a TWRP-Backup to my sdcard, because i formatted my sdcard to „internal“)
or will it break things?

Thanks!

:-) AK

**Comment by Kra1o5** [comment]
Hi @halloalexkern ,

With this you will relock bootloader.

I make some updates to kernel maybe it helps to this issue.

**Comment by akamkomputer** [comment]
So i'd have to flash the complete 3.2.9-fireware-update ... and the start from scratch with unlocking and flashing to cm-13, right? 
(i still emeber that last time, when i bricked my M5 permanetly with the 3.2.2. firmware-update :-( ... luckily i got a free replacement from BQ!)

But do you think i'd be necessary for your cm13 to update to 3.2.9? or should 3.2.2 also work?

:-) AK

**Comment by Kra1o5** [comment]
Hi @halloalexkern ,

I think you will be fine with 3.2.2 firmware so not need to change firmware.

**Comment by akamkomputer** [comment]
Thanks.

... about the freezes: would a dmesg help? or do you already have an idea what could cause it?

:-) AK

**Comment by akamkomputer** [comment]
i'm pretty sure this issue is gone with 2016/03/2.
I haven't expected any more freezes.

Thanks!!

**Comment by DerSaxxe** [comment]
Should you close this issue?

**Comment by Kra1o5** [comment]
Hi @SIRSteiner, yes we can reopen if needed.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#63
