### ISSUE TITLE
Problem with vibration CM13

### ISSUE THREAD

**Issue by cristianss98** [piccolo-dev/android_device_bq_piccolo#64]
The vibration does not work in this last update, I use a lot because I do not like having the phone in sound.
Thank you. ;-)

**Comment by Kra1o5** [comment]
Hi @cristianss98 ,

Can you try changing the vibration intensity (Settings/Sounds) ?

**Comment by cristianss98** [comment]
Hi @Kra1o5
I tried to change the settings and also tried with an application to see if vibrated but nothing.

**Comment by Kra1o5** [comment]
Really weird, because @eloimuns try it & reports working fine.

Can you do a wipe cache/wipe dalvik cache in twrp?

**Comment by cristianss98** [comment]
I did wipe cache and Dalvik cache in TWRP and still does not work.
The only thing left is wipe data and reinstall the ROM

**Comment by Kra1o5** [comment]
Wait for todays build to try.

**Comment by cristianss98** [comment]
Ok,

Thank you very much ;-)

**Comment by cristianss98** [comment]
I solved the problem, reinstall the latest official firmware BQ and then I install CM13 and next day vibrated again normally.
PS: sorry for my mistranslations.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#64
