### ISSUE TITLE
CM13 camera hdr mode on, makes double photos

### ISSUE THREAD

**Issue by Greatdroid** [piccolo-dev/android_device_bq_piccolo#65]

**Comment by Kra1o5** [comment]
Yes, we are using hybrid blobs.

**Comment by Greatdroid** [comment]
Ok thanks.

**Comment by cmorlok** [comment]
Confirmed. Seems to be a Snap issues. Other cameras (tested with GoogleCamera and OpenCamera) save pictures only once.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#65
