### ISSUE TITLE
cm13 apollo music player not working properly on car bluetooth

### ISSUE THREAD

**Issue by Greatdroid** [piccolo-dev/android_device_bq_piccolo#66]

**Comment by Kra1o5** [comment]
You refer to Eleven right?

**Comment by Greatdroid** [comment]
Sorry don't get it. What do you mean by eleven?

**Comment by Kra1o5** [comment]
CM not using Apollo from CM12.1+, now use Eleven.

**Comment by Greatdroid** [comment]
Sorry didn't know they changed the name, but yes, I mean that one. :-)

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#66
