### ISSUE TITLE
exchange kind account has gone

### ISSUE THREAD

**Issue by starvoid** [piccolo-dev/android_device_bq_piccolo#68]
I upgraded to cm-13.0-20160313 from 13.0-20160306. My configured exchange account has gone.

When I tried to add a new account, in the step to choose the kind of account, the interface doesn't show exchange type (it shows imap and pop3 options only)

Please, could you check it?

Thanks for great job.

**Comment by eloimuns** [comment]
which gapps are you using?

**Comment by starvoid** [comment]
open_gapps-arm-6.0-nano-20160113.zip.

Hi, the problem has vanish installing cm-13.0-20160320.

It's a little weird, but I have my exchange account working again.

From my side, this issue is closed. I leave it open just in case you want to check it, but, please, fell free to close it.
