### ISSUE TITLE
logcat issues

### ISSUE THREAD

**Issue by andresako** [piccolo-dev/android_device_bq_piccolo#69]
Hi, before all, thanks for that great Rom.

I'm a programing developer and I need to work a lot with logcat to debug my app's.
After installing cm-13.0-20160313 I had the clock issues, not a big problem,
I update to cm-13.0-20160320 and now my logcat is going crazy, I'll explain that:

First I have random errors with SQLite:  

(3 / 5 minutes between)

> 6105-6124/? E/SQLiteLog﹕ (13) statement aborts at 12: [INSERT INTO app_event(session_id,occurtime,paramap,event_label,event_id) VALUES (?,?,?,?,?)]
> 03-23 09:34:49.709    6105-6124/? E/SQLiteDatabase﹕ Error inserting session_id=6be46694-8c2b-464c-a60c-726a3490a4e3 occurtime=1458722089673 paramap=[B@90b46b event_label=null event_id=__tx.env
>     android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
>             at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
>             at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
>             at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
>             at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
>             at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
>             at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
>             at com.tendcloud.tenddata.aj.a(Unknown Source)
>             at com.tendcloud.tenddata.i.d(Unknown Source)
>             at com.tendcloud.tenddata.i.a(Unknown Source)
>             at com.tendcloud.tenddata.c.handleMessage(Unknown Source)
>             at android.os.Handler.dispatchMessage(Handler.java:102)
>             at android.os.Looper.loop(Looper.java:148)
>             at android.os.HandlerThread.run(HandlerThread.java:61)

My second error is geoposition related, after turn on GPS with high accuracy, the logcat started to put a lot of redlines of code without stop, repeating:

> 03-23 09:39:43.266    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_msg_process_system_update(UlpSystemEvent) line 1455
> 03-23 09:39:43.266    2838-4065/? E/LocSvc_libulp﹕ I/int ulp_msg_process_system_update(UlpSystemEvent): systemEvent:5
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_process_system_update(UlpSystemEvent) line 2352
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_select_providers() line 333
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_turn_onoff_quipc_provider() line 700
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_quipc_stop_engine() line 235
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_quipc_engine_running() line 60
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_turn_onoff_gnss_provider() line 595
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_gnss_stop_engine() line 262
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_quipc_engine_running() line 60
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_turn_onoff_gnp_provider() line 496
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_gnp_engine_running() line 59
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_gnp_stop_engine() line 195
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_gnp_engine_running() line 59
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_gnp_engine_running() line 59
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_brain_turn_onoff_zpp_provider() line 437
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_zpp_stop_engine() line 174
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> bool ulp_zpp_engine_running() line 62
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/===> int ulp_msg_process_start_req() line 447
> 03-23 09:39:43.267    2838-4065/? E/LocSvc_libulp﹕ I/int ulp_msg_process_start_req(), at ulp state = 1

That's normal?
AK

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#69
