### ISSUE TITLE
64bit?

### ISSUE THREAD

**Issue by piwats** [piccolo-dev/android_device_bq_piccolo#7]
Qualcomm 615 is a 64 bit cpu, armv8, isn't it?

So why does BoardConfig.mk (bq?) insists on using armv7?

```
# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53

TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
```

**Comment by piwats** [comment]
Examples of 64bit BoardConfig.mk for the 615:

https://github.com/sonyxperiadev/device-sony-kanuti/blob/master/BoardConfig.mk
https://github.com/Silentlys/android_device_zte_N939St/blob/master/BoardConfig.mk

**Comment by Kra1o5** [comment]
I know how to compile 64 bits but we cant do it.

We have blobs for 32 bits not for 64 bits.

Greetings

**Comment by stucki** [comment]
Check this folder for proprietary files that are not available in source and exist only for 32bit platforms:
https://github.com/piccolo-dev/proprietary_vendor_bq/tree/cm-12.1-test/piccolo/proprietary

This means, we depend on BQ for this.

On the other hand, you won't gain anything by switching a 2GB / 3GB RAM device to 64bit.

**Comment by piwats** [comment]
ah, o.k. I understand, bq itself is the limiting factor here...

It is not a question about the memory access.

ARMv8 has some simd improvements, as well as some instructions added (i.e. crypto), should be a bit faster, too.

Is it possible to take the blobs from the repo for the zte n939St (does the sony repo help? They actually have instructions how to build AOSP, the repo seems to be for the m4 aqua), at least, it is the same platform as piccolo?

**Comment by Kra1o5** [comment]
Not, we have specific blobs (like Camera).

**Comment by piwats** [comment]
Any contacts to bq?

**Comment by piwats** [comment]
Also, there ist this 615 based device officially supported by cyanogenmod:

https://github.com/cyanogenmod/android_device_yu_tomato

IMX214 is the same camera as on nexus 6/ oneplus 2, seems there is some src in cyanogenmod for it.

**Comment by Kra1o5** [comment]
Is more difficult than this, IMX214 have different EEPROM and differents configs.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#7
