### ISSUE TITLE
CM13 file manager doesn't show OTG-Devices

### ISSUE THREAD

**Issue by DerSaxxe** [piccolo-dev/android_device_bq_piccolo#70]
Maybe a CM issue?

**Comment by Kra1o5** [comment]
Pretty sure yes.

@eloimuns can test it you too?

**Comment by eloimuns** [comment]
Seems to be a CM problem. I just tested with Xiaomi Redmi 1S and Xiaomi mi4 and the same result.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#70
