### ISSUE TITLE
Bluetooth mic volume too low

### ISSUE THREAD

**Issue by mikellinares** [piccolo-dev/android_device_bq_piccolo#71]
Hi,
When the M5 (CM13 last update) is connected to a intercom using BT, the mic volume is too low. The person in the other side cannot hear me.
I have been making diferent tests with other mobile devices and same intercom. The problem occurs only with my two BQ M5 and this ROM. I can´t confirm if this error occurs with the stock ROM. 
Thanks for supporting ;)

**Comment by Kra1o5** [comment]
Hi @mikelgaldakao ,

We will check it for next release :)

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#71
