### ISSUE TITLE
Awesome consuming of ram cm13 (Screensaver)

### ISSUE THREAD

**Issue by andresako** [piccolo-dev/android_device_bq_piccolo#72]
Since using the screen saver , the ram has skyrocketed.
I'm using the last comp of this rom, I think that's not normal
attached screenshot

Thanks for all :)

![photo_2016-04-01_08-39-40](https://cloud.githubusercontent.com/assets/9285655/14199561/c83fac54-f7e5-11e5-904d-2b3eab7da532.jpg)

**Comment by cristianss98** [comment]
could be a mistake, anyway if you get upset or consume everything that says you pobrar to uninstall it if you're root with Link2SD.

**Comment by andresako** [comment]
Yeah,for now I've stopped using that and the ram usage seems to be normal again.
I mention only for creators to take this into account in later builds.

**Comment by Kra1o5** [comment]
Hi @andresako ,

I will check it but probably upstream bug.

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#72
