### ISSUE TITLE
Touchscreen errors

### ISSUE THREAD

**Issue by ghost** [piccolo-dev/android_device_bq_piccolo#73]
When in lockscreen, the phone wont respond properly, and when you finally unlock the phone, some lockscreen overlay appears and it wont disappear until you tap the screen, thus making it a little annoying
Thanks!

**Comment by 1tft** [comment]
I also recognized this "overlay" in 2016/04/03 build. Sometimes I see a very little phone icon on the left buttom area, too. At afternoon I was faced with a total freeze of the phone during navigation with G-Maps (I had to press the power button over 10minutes to initiate a reboot). Than I downgraded to 2016/03/27.

**Comment by ghost** [comment]
I'm installing xposed, I'll see  if it's still appearing

**Comment by Kra1o5** [comment]
Hi, 

Is upstream issue not device specific and yeah is really annoying.

Greetings

**Comment by ghost** [comment]
Seems like it auto fixed, i didnt see it anymore

**Comment by Kra1o5** [comment]
Fixed upstream: https://github.com/CyanogenMod/android_frameworks_base/commit/16a065df515225bf4da78df7ccea63ca860b2b20

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#73
