### ISSUE TITLE
both SIMs switch to roaming when only one of them should

### ISSUE THREAD

**Issue by stefanocostantini** [piccolo-dev/android_device_bq_piccolo#74]
I have Spanish (Tuenti) and UK SIMs as i travel between these two countries. When both SIMs are inserted, the Spanish SIM switches to 2G Roaming (it should be LTE on the Movistar network). As a result I lose data connection, because the SIM setting is for data roaming turned off. However, turning it on does not restore the data connection, as the phone insists on connecting on a 2G Movistar network. 

Note that I always switch the mobile data to the SIM of the country where i'm in.

The problem goes away when the other SIM is removed. This issue occurs only in Spain, but not in the UK where the behaviour is as expected. 

The issue existed in 12.1 but only if the phone rebooted when connected to wifi. In that case, the solution was to disconnect wifi and then de-activate the spanish SIM. Unfortunately the option to de-activate a SIM has been removed in 13.

**Comment by Kra1o5** [comment]
Yes, probably CM get the feature back soon.

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#74
