### ISSUE TITLE
OpenGL ES 1 (GLES1) performance is bad

### ISSUE THREAD

**Issue by sergiopoverony** [piccolo-dev/android_device_bq_piccolo#75]
Gles1 game more lags for example XASH3D  - maybe proprietary drivers adreno

**Comment by stucki** [comment]
No idea what you're talking about. Please be more specific.

**Comment by sergiopoverony** [comment]
I install old game. Game use only Gles1. Xash3D game name - this is HalfLife 1 launcher https://github.com/SDLash3D/xash3d. My old device mtk6579 PowerVR 540 - show fps 90!!! this is device 17-23fps. On CM13 - not start - close app after run.
I check all version  firmware - official 5.0 5.1 cm12 cm13

**Comment by sergiopoverony** [comment]
This is more specific?

**Comment by cmorlok** [comment]
Gles1 is fully working, verified using
https://play.google.com/store/apps/details?id=yz.opengl.es11

**Comment by sergiopoverony** [comment]
Yep. Worked and low fps. This very simple test. In game use more faces and texture.

**Comment by sergiopoverony** [comment]
My OLD device - this is minimal FPS  - max FPS over 75-80
![screenshot_2016-04-12-17-20-18](https://cloud.githubusercontent.com/assets/5286127/14459772/51918784-00d3-11e6-9765-a309ae6c19e4.jpg)

**Comment by sergiopoverony** [comment]
This is NEW bq M5 this device 
![screenshot_2016-04-12-17-15-30](https://cloud.githubusercontent.com/assets/5286127/14459793/79daab26-00d3-11e6-87f8-3e9d40cf5a26.jpg)

**Comment by cmorlok** [comment]
It would be helpful if you'd tell us the name of your old device.

I just did some benchmarks. For OpenGL 2 and 3, we have the same
performance like any other phone with this chipset.

**Comment by sergiopoverony** [comment]
All my old devices china tablet and phone. TabletPC - Pipo M8Pro RK3188 MALI MP4 (fps >50) and Phone - JayYou  G3S MTK5989T PowerVR 450(i dont know) fps >50/ My Wife use Samsung Galsaxy A3 (2015) FPS >55
I know Gles2 and  3 - Real good work. Gles1 - is bad working/ This Game use ./system/lib/libGLESv1_CM.so - maybe him bad work?  May be him MustDie under FHD screen resolution?

**Comment by cmorlok** [comment]
I will take a look. Maybe the so files do not fit together.

Can you please run some benchmarks in https://play.google.com/store/apps/details?id=yz.opengl.es11 (some tests where it shows the FPS) on one of your other phones? I need some reference values, but I haven't found any recent GLES1 benchmark.

**Comment by sergiopoverony** [comment]
Oh. I check on all my devices. No different fps in test.

**Comment by eloimuns** [comment]
Did you test it when device is plugged in? Maybe the problem is here.

**Comment by sergiopoverony** [comment]
> plugged in? What? PC, ADB, OTG i'm Russian user and i bad speak english
> I test witchout  usb connections

**Comment by eloimuns** [comment]
you can try while not charging ?

**Comment by sergiopoverony** [comment]
I test all witchout usb connections, charging and etc - i write about it in up message ^

**Comment by sergiopoverony** [comment]
##### Men. After change screen resolution (https://play.google.com/store/apps/details?id=com.nexter.miniscaler) I change Width to 540px and Height to 960. DPI change to 248. FPS in game - 40-60 ROFL.

Gles1 driver not work under FHD screen resolution? WTF (sorry)
 Crazy crutch

### This Big problem!

**Comment by Kra1o5** [comment]
Hi,

Can you try changing dpi in Settings/Screen & report the results?

I recommend to use standard dpi values.

Greetings

**Comment by sergiopoverony** [comment]
Hi.
1. I change only DPI - no effct.
2. I change resolution - good work.
3. I change resolution and DPI - good work.

This is badwork GLES1 under hight screen resolution (default 1920*1080)

**Comment by sergiopoverony** [comment]
helloooo

**Comment by Kra1o5** [comment]
Hi,

We are using latest adreno gpu blobs from MM.

So at the moment we cant do much more.

**Comment by sergiopoverony** [comment]
sad and melancholy

**Comment by Kra1o5** [comment]
Dont worry we will see if we can improve it.

**Comment by cmorlok** [comment]
Is there any Gles1 benchmark available which we can use for testing?

**Comment by sergiopoverony** [comment]
Yes, Of course. We make standalone apk file for test. I drop referal link here for download and test

**Comment by sergiopoverony** [comment]
HI all. we make special for you Uplink HalfLIfe apk https://goo.gl/QyuuhP (~40mb)
On all devices FPS - 60-80
Aquaris M5 -25-30
Welcome for test and  great fix for your
You can play NewGame or Hazard Course
Sorry my English i from Russia

**Comment by sergiopoverony** [comment]
What news?)

**Comment by Kra1o5** [comment]
Sorry, Im busy at the moment so not checked yet.

Greetings

**Comment by insestito** [comment]
on xda you have an post for improve a lot all graphics of all android devices

**Comment by sergiopoverony** [comment]
We test on more devices. After it i write message here. If you want - you can made post on XDA.

**Comment by insestito** [comment]
en xda hay un post dedicado a un "mod" para mejorar los drivers de los graficos o algo asi

**Comment by sergiopoverony** [comment]
I dont understand you english. i use google translate/ give me link on XDA tree )

**Comment by sergiopoverony** [comment]
HELLO MEN AGAIN. Sorry caps ))) 
Now after official update (in official FW - android 6) Gles1 work is FINE.
Next Question - how long wait for CM13 this fixes?

**Comment by eloimuns** [comment]
Yesterday build have this fixes but have a data issue.. 

 wait for today build ;)

**Comment by sergiopoverony** [comment]
Good news. Thn you

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#75
