### ISSUE TITLE
NoData-SIM no signal when there is 2G or 2,5G and it is configured as 2G

### ISSUE THREAD

**Issue by Mutilo** [piccolo-dev/android_device_bq_piccolo#76]
I have two SIM (Spain), one of Mundo-R with data, and other of Movistar without data:
- If I put the R SIM in slot 1, the Movistar not covered.
- If I do the reverse, I put the Movistar in slot 1, both are covered, but Movistar loses and not recovered.

As Movistar has no data I have to put the 2G (and R 3G or LTE), but when there are bad signs, it lost and not recovered, and does not receive calls. When I put on R SIM 3G or LTE, on Movistar only allow 2G.

If I put only Movistar SIM, and set up with 3G, it works correctly when there are bad sign.

It's a bug? What is the best configuration to work properly? What "type preferred network" will assign to each?

**Comment by cmorlok** [comment]
You don't have a choice. Only one SIM can be in 3G/LTE mode, the other one has to be in 2G mode.

Regarding the connection loss: I experience this as well. I had the same problem on stock, so I'm not sure if it's a software or a hardware issue. Interestingly, you can't get the connection back with manual network selection, even if the search finds the network.

**Comment by Mutilo** [comment]
Indeed. One SIM in 3G/LTE mode, and the other one in 2G mode.

But when the SIM 2G loses the connection because there are bad/low/no coverage, no recovers it. There are many people who are using two SIM's on stock and doesn't have this issue.

I need to use two SIM, is there any way to fix this problem or I have flash another ROM?

**Comment by cmorlok** [comment]
From time to time I flash the latest stock for some comparisons. I always had exactly the same bad behavior on stock with the SIM in 2G mode. And there are some posts where people are describing similar issues on stock, e.g. http://www.android-hilfe.de/thema/wie-ist-eure-empfangsqualitaet-beim-bq-m5.732693/.

**Comment by Mutilo** [comment]
In this post (http://www.htcmania.com/showpost.php?p=22467455&postcount=912) they said it worked well, so I reported the bug

**Comment by cmorlok** [comment]
Doesn't your linked post say that dual SIM is working with CM13?

**Comment by Mutilo** [comment]
`Buenas, si funciona el dual SIM en CM13, yo lo tengo y funciona perfectamente (mensajes, llamadas...)`

I understand that he would work correctly...

**Comment by Mutilo** [comment]
Sorry. I think I was wrong. In fact, coverage is restored when it lose the signal.
The issue is that when I set "NOData-SIM" as 2G and there is little/poor coverage (e.g. in the "Data-SIM" shows G or E), NoData-SIM has no coverage (0%)
But, in the same place, if I set NoData-SIM as 3G, it has coverage to make and receive calls.

**Comment by Kra1o5** [comment]
We need to check this, thanks for the report.

**Comment by cmorlok** [comment]
Can you ask bq's support team if they know this issue? On my phone, I see this on all ROMs (stock, CM12.1, CM13). It seems to be either a hardware issue, or there is a problem with the blobs.

**Comment by Mutilo** [comment]
As I use CM13, bq's support can't help me.
This only happens when I set the NoData-SIM as GSM/2G, coverage's bar is worse or null than if I set as 3G/LTE in the same place

**Comment by cmorlok** [comment]
Sorry, I replied to @Kra1o5. Can you look if this is a known issue? 

@Mutilo: of course the coverage is better when you set the SIM to LTE. Then the phone decides depending on the signal strength whether it connects to 4G, 3G or 2G. When set to 2G it can't connect to 3G or 4G.

**Comment by Mutilo** [comment]
And could set a ROM's configuration to set both SIM to 3G and set only one to "Mobile data"

**Comment by cmorlok** [comment]
No, it's a hardware restriction.

**Comment by Kra1o5** [comment]
Yes, hardware limitation.
One of the slot need to be in 2G only.

**Comment by cmorlok** [comment]
It think we have a general issue with the connection quality. At the moment my first SIM is on roaming. The second SIM is a local one. I don't get any signal on both SIMs. Even a manual network search doesn't return any result. My old Moto G2 has full signal on both SIMs.

**Comment by Kra1o5** [comment]
Hi,

Well, we are using LP firmware, blobs & hybrid kernel.

So when official Marshmallow update comes out.

We will fix the big part of actual issues.

Greetings

**Comment by stefanocostantini** [comment]
I have to say that this seems to be getting worse. It wasn't an issue on earlier builds but now I'm struggling to get any coverage unless it's very strong. Any suggestions?

**Comment by Kra1o5** [comment]
Sorry, Im using X5 at the moment with 3G.

I will test it asap but not changes from our side so maybe upstream...

Greetings

**Comment by stefanocostantini** [comment]
Yes, fingers crossed!

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#76
