### ISSUE TITLE
SystemUI crashes in UI Tuner (aka Edit Tiles)

### ISSUE THREAD

**Issue by GautierLePire** [piccolo-dev/android_device_bq_piccolo#78]
Hey,

I flashed last update (17th April), GApps (Pico, 21st April) and XPosed (v82, no GravityBox)
When I click "Edit Tiles" > "(+)" > Scroll the list, SystemUI crashes
![screenshot_20160422-131250 1](https://cloud.githubusercontent.com/assets/6824634/14740057/41387fda-088c-11e6-95be-b244b809a315.png)

The bug wasn't present in v20160320

Thank you in advance

**Comment by GautierLePire** [comment]
Bug solved by factory reset.

(Probably caused by restoring data from old version)

Sorry for the inconvenience.

EDIT:

Did nothing, crashes again

No need to scroll to make it crash, simply press (+)

EDIT2:

The bug is present on v10/4, but less frequent.
(Only crashes when deleting tiles, but it still deletes so not a problem)

**Comment by ixti** [comment]
Having same issue. Fails for me every time I scroll at some point (after exact element).

![screencast](https://cloud.githubusercontent.com/assets/94782/14748731/b9508858-08bb-11e6-8a3d-c3918d16f089.gif)

Constantly fails for me after "Invert colors" element

**Comment by GautierLePire** [comment]
The problematic element might be the next one, "Lock Screen" in stock version
(icon load fails?)

**Comment by Kra1o5** [comment]
Yes, is upstream issue.

It will be fixed in next build.

Greetings

**Comment by ixti** [comment]
Awesome! @Kra1o5 thanks!

**Comment by ixti** [comment]
After upgrade to 20160424 all works perfectly fine! Thanks!

**Comment by eloimuns** [comment]
Perfect, 

We will close this issue

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#79
