### ISSUE TITLE
Can't record calls

### ISSUE THREAD

**Issue by Mutilo** [piccolo-dev/android_device_bq_piccolo#79]
Hi.

Stock ROM can record calls with any app. Why CM13 can't record?

Is there any way or app to automatic record?

**Comment by Kra1o5** [comment]
Hi,

You can make it from dialer in actual call.

If you are in whitelist country.

**Comment by Mutilo** [comment]
But to automatically record?

**Comment by Kra1o5** [comment]
Probably not.

**Comment by Mutilo** [comment]
And could add a patch to the ROM?

**Comment by Kra1o5** [comment]
We want to have the ROM as close as original source.

**Comment by Mutilo** [comment]
Ok. Thank you

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#80
