### ISSUE TITLE
irregular reboots

### ISSUE THREAD

**Issue by 205er** [piccolo-dev/android_device_bq_piccolo#8]
Hi,

my device reboots from time to time using the last CM-build (04.10.2015).
So far, it allways happend when the m5 was in sleep mode (display switched off).

Can I provide any additional information, that might help to resolve this issue?

Bye

**Comment by Kra1o5** [comment]
Some people fix this by increase minimun frequencies of cores.

Can you try it?

**Comment by 205er** [comment]
I will give this a try.
Using trickster mod, i increased the min. CPU Freq. to 345MHz. Hopefully it will not result in a shortened battery life time ;-)

**Comment by 205er** [comment]
Increasing the minimum CPU frequency does not help! I had another reboot some minutes ago :-(
Any other idea?
Wouldn't a system log help to analyze this problem?

**Comment by Kra1o5** [comment]
Well , logcat after reboot doesnt help & we dont have last_kmsg.

You can record with app CatLog.

**Comment by DerSaxxe** [comment]
Today I had no reboot but the M5 got hot and did a shutdown. I have a 37 MB log file (zip 3.7 MB). Please look at your mails there you can find the download link. Many thanks

**Comment by Kra1o5** [comment]
Ok, thanks! 

I will take a look into it asap.

Greetings

**Comment by Kra1o5** [comment]
@SIRSteiner ,

After check logs I can say the reboots are caused by memory overflow (Out of memory).

This is a big problem of LP in general, for next release I will try to optimize it.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#8
