### ISSUE TITLE
No weather source selected Cclock widget

### ISSUE THREAD

**Issue by andresako** [piccolo-dev/android_device_bq_piccolo#83]
Since last update (Monday 9), my cclock widget doesn't find a weather source.
Previously, I haven´t any weather program and work perfectly.

I try to install "weather underground" cuz its compatible with CM13, and still without find a weather source :(

![image](https://cloud.githubusercontent.com/assets/9285655/15144526/355ec07a-16b0-11e6-8279-f285ad3f7e3b.png)
![image](https://cloud.githubusercontent.com/assets/9285655/15144531/3bfadb26-16b0-11e6-98ed-85096fd27b5e.png)

**Comment by stucki** [comment]
This is not a bug. Just install the Yahoo weather provider:
https://play.google.com/store/apps/details?id=org.cyanogenmod.yahooweatherprovider

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#84
