### ISSUE TITLE
CM13 wrong autoupdate notification

### ISSUE THREAD

**Issue by danny9484** [piccolo-dev/android_device_bq_piccolo#85]
I have set the check for update feature in the settings app to every day and it gives me a notification that a new update is available even though there isn't. If I go to the settings and check for updates manually it tells that none are available but on the notification I can press download and it install the same version again.

**Comment by stucki** [comment]
I can confirm this. Happens to me every day :)

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#86
